import Head from "next/head";
import TodoItem from "../components/todoItem";
import { supabase } from "../utils/supabase";

export async function getServerSideProps(ctx) {
  // Fetch all the available todos
  let { data: todos, error } = await supabase.from("todos").select("*");

  return {
    props: {
      todos,
    },
  };
}

export default function Home({ todos }) {
  return (
    <div>
      <Head>
        <title>Supatodo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center justify-center  max-w-3xl mx-auto mt-20 ">
        <h1 className="text-5xl font-bold mb-6">Todos 🚀</h1>

        <div className="my-6 w-full flex items-center justify-between space-x-3 p-2">
          <input
            type="text"
            className="border rounded-sm border-gray-800 w-full p-2 outline-none bg-[#232323] font-semibold"
            placeholder="Write todo "
          />
          <div className="border py-2 px-4  cursor-pointer rounded-sm border-gray-800 hover:bg-gray-800">
            Add
          </div>
        </div>

        <div
          className="
             p-2 flex flex-col space-y-3 w-full"
        >
          {todos?.map((todo) => (
            <TodoItem key={todo.id} text={todo.todo} />
          ))}
        </div>
      </div>
    </div>
  );
}
