import { useRef, useState, useEffect } from "react";
import Head from "next/head";
import TodoItem from "../components/todoItem";
import { supabase } from "../utils/supabase";

export default function Home() {
  const inputRef = useRef(null);
  const [todos, setTodos] = useState([]);

  // Fetching all the todos
  useEffect(() => {
    const fetchTodos = async () => {
      let { data: todos, error } = await supabase.from("todos").select("*");
      setTodos(todos);
    };
    fetchTodos();
  }, [todos]);

  // Adding a new todo
  const addTodoToSupabaseDB = async (e) => {
    e.preventDefault();
    const { data, error } = await supabase
      .from("todos")
      .insert([{ todo: inputRef.current.value }]);

    inputRef.current.value = "";
  };

  return (
    <div>
      <Head>
        <title>Supatodo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex flex-col items-center justify-center  max-w-3xl mx-auto mt-20 ">
        <h1 className="text-5xl font-bold mb-6">Todos 🚀</h1>

        <div className="my-6 w-full flex items-center justify-between space-x-3 p-2">
          <input
            type="text"
            className="border rounded-sm border-gray-800 w-full p-2 outline-none bg-[#232323] font-semibold"
            placeholder="Write todo "
            ref={inputRef}
          />
          <div
            className="border py-2 px-4  cursor-pointer rounded-sm border-gray-800 hover:bg-gray-800"
            onClick={addTodoToSupabaseDB}
          >
            Add
          </div>
        </div>
        <div
          className="
             p-2 flex flex-col space-y-3 w-full"
        >
          {todos?.map((todo) => (
            <TodoItem key={todo.id} todo_id={todo.id} text={todo.todo} />
          ))}
        </div>
      </div>
    </div>
  );
}
